version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=your_db_host
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_DATABASE=crm
      - DB_PORT=5432
      - JWT_SECRET=your_jwt_secret
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
